### ISSUE TITLE
Javascript API.

### ISSUE THREAD

**Issue by bas080** [2rhop/vollk#1]
I am liking the CLI you have created.

I would like it if I could define those specs and running them using some kind of Javascript API.

```js
const vollk = require('vollk')
const pick = require('pick') // random pick example fn

const locationSpec = vollk.spec('location', {
  name: ['lorem', 'name'],
  id: 'hash', 
  currency: pick(['euro', 'dollar']
})

vollk.seed(locationSpec, Number.MAX_SAFE_INTEGER),then(() => 'completed')
```

**Comment by 2rhop** [comment]
Hello @bas080  i am working on your issue, but what do you mean with **_'location'_** ? this is what i have for now:

```javascript
const vollk = require('vollk')

//setting the properties of the table whose gona be seeded. 
//this is the syntax (**field** : _'faker.type'_)
var foo = {
    title: "lorem.word",
    description: "lorem.sentence"
};

//creating the spec (name_of_table, properties)
var mySpec = vollk.spec('test', foo),
      queries = 5

//calling the async function seed()
vollk.seed(mySpec, queries).then((res) => {
    console.log('done seeding on table: ' + res)
}).catch((err) => {
    console.log(err)
})
```

Tell me if it works for you and i will update the version

**Comment by bas080** [comment]
`location` would be the table to write to. You have named the table `test`.

I see little use for responding with the table name. Consider responding with some data that relates to the the insertion. I'm not exactly sure what makes sense. If you are not sure either then just respond without a value (`undefined`).

Also note that my example shows a way to opt out of the faker API. The opt out feature is handy whenever the random function is not part of faker. I do this by allowing one to pass a function as value generator.

Another concern I have with the Vollk API is that it locks you into using the faker API. What if I want to write a constant string to the table. How would I define that? Sometimes the value of one field depends on the value of another. How would one define that in the spec. I should probably make separate tickets for these. Regardless I'll mention it now before this API is finalized.

The rest of the API you propose makes sense.

It might be nice to implement a stream API which allows you to be able to see the generated data before inserting it into database and more importantly, see the database response of several insertions by using a writable stream. Also this would be a separate issue.

Concerning streaming I am proposing something like this.

```js
vollk.seedStream(mySpec, doSomethingWithRandomObjectFn,  Number.MAX_SAFE_INTEGER)
  .pipe(doSomethingWithTheKnexInsertionResponses)
```

Reason why streams would be a good fit has to do with the goal of Vollk, to support **large** amounts of fake data. It also nice to have access to the randomly generated objects. Some applications/tests might want to perform additional operations using the generated fake data, or the responses of the databases.

**Comment by 2rhop** [comment]
I appreciate your suggest , i will try to implement something that fits what you want, _thanks_


**[note]:** you can add a new feature by implementing that in vollk and then we can see the results

**Comment by 2rhop** [comment]
closing this issue and moving [here ](https://github.com/2rhop/knex-seeder/issues) to the new project
